### ISSUE TITLE
Trouble when rolling up RDFa report

### ISSUE THREAD

**Issue by rubensworks** [gkellogg/earl-report#4]
I just tried rolling up the RDFa document with this tool, but I seem to be running into some problems.

1. I can't seem to find how to define multiple manifests, only a single `--manifest` option value is possible (as expected). Using the root manifest at `test-suite/manifest.jsonld` does not seem to be working though. Is there another way to pass these manifests?

2. When generating the HTML, I get the following error:

```
Traceback (most recent call last):
	11: from /usr/local/bin/earl-report:23:in `<main>'
	10: from /usr/local/bin/earl-report:23:in `load'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/earl-report-0.4.6/bin/earl-report:98:in `<top (required)>'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/earl-report-0.4.6/lib/earl_report.rb:459:in `generate'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/haml-5.1.1/lib/haml/engine.rb:130:in `render'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/haml-5.1.1/lib/haml/engine.rb:130:in `eval'
	 5: from (haml):360:in `block in render'
	 4: from (haml):360:in `each_with_index'
	 3: from (haml):360:in `each'
	 2: from (haml):384:in `block (2 levels) in render'
	 1: from (haml):384:in `each'
(haml):387:in `block (3 levels) in render': undefined method `has_key?' for "http://greggkellogg.net/foaf#me":String (NoMethodError)
```

This can be fixed by removing all occurrences of `http://greggkellogg.net/foaf#me`.
Is there a better solution to this problem?

3. Is there a template available for generating the RDFa HTML report? As my current output has a bit of minor styling differences compared to the existing file.

These are the scripts I am using:
```sh
earl-report --format json \
	--manifest ../test-suite/test-cases/rdfa1.1/html4/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1/html5/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1/svg/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1/xhtml1/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1/xhtml5/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1/xml/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1-proc/xml/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1-role/xml/manifest.ttl \
	--manifest ../test-suite/test-cases/rdfa1.1-vocab/xml/manifest.ttl \
	--base http://rdfa.info/test-suite --name "RDFa 1.1" --bibRef [[RDFA-CORE]] \
	-o earl.jsonld \
	clj-rdfa*.ttl earl-rdfastreamingparser*.ttl easyrdf*.ttl greenturtle*.ttl java*.ttl librdfa*.ttl pyrdfa*.ttl rdf-rdfa*.ttl semargl*.ttl

earl-report --json --format ttl -o earl.ttl earl.jsonld

earl-report --json --format html -o index.html earl.jsonld
```

**Comment by gkellogg** [comment]
There is a bit of versionitis with the files in the RDFa test suite. I'm updating them now. Also, the dependencies for this gem are out of date, I've released an update. (I'll have some updates to the RDFa repo to update some reports to be consistent with the gem behavior).

**Comment by rubensworks** [comment]
Thanks! This seems to work now.
See https://github.com/rdfa/rdfa.github.io/pull/28 for the PR.
